---

- hosts: all
  remote_user: root

  handlers: 

    - name: restart postgresql
      service: 
        name: postgresql
        state: restarted

  tasks: 

    - name: Upgrade Debian
      apt: 
        update_cache: yes
        upgrade: "yes"

    - name: Install extra
      apt:
        name: 
          - curl
          - apt-transport-https
          - dirmngr
          - aptitude
        state: present

    - name: Add PostgreSQL Repo Key
      apt_key: 
        id: 7FCC7D46ACCC4CF8
        keyserver: keyserver.ubuntu.com

    - name: Add Citus Repo Key
      apt_key: 
        id: 0D750985D6AF6C22
        url: https://repos.citusdata.com/community/gpgkey

    - name: Add Postgresql Repository
      apt_repository:
        repo: deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main
        state: present

    - name: Add Citus Repository
      apt_repository: 
        repo: deb https://repos.citusdata.com/community/debian/ stretch main
        state: present

    - name: Install citus
      apt:
        name: 
          - postgresql-12-citus-9.2
        state: present

    - name: Configure PostgreSQL to listen on all interfaces
      lineinfile:
        path: /etc/postgresql/12/main/postgresql.conf 
        insertbefore: '^port = '
        create: yes
        line: "listen_addresses = '*'"
      notify: restart postgresql

    - name: Configure PostgreSQL to listen on all interfaces
      template:
        src: files/pg_hba.conf
        dest: /etc/postgresql/12/main/pg_hba.conf
      notify: restart postgresql

#    - name: Display all variables/facts known for a host
#      debug:
#        var: hostvars[inventory_hostname]

# vim: ts=2 et nowrap autoindent
